# General
set -g mouse on
set-window-option -g mode-keys vi
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Status bar
set -g status-position top
set -g @tmux2k-theme 'duo'
set -g @tmux2k-icons-only true
set -g @tmux2k-show-powerline false
set -g @tmux2k-enable-popups false

set -g @tmux2k-left-plugins "session cwd"
set -g @tmux2k-cwd-icon ""

set -g @tmux2k-right-plugins "time"
set -g @tmux2k-time-icon ""

# Keybinds
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux config reloaded"
bind -n C-n new-window
bind m set -gF mouse '#{?mouse,off,on}' \; display "mouse: #{?mouse,on,off}"
# panel
unbind v
unbind h
unbind %
unbind '"'
bind -n C-w kill-pane
bind ] split-window -h
bind [ split-window -v

bind h select-pane -L
bind k select-pane -D
bind j select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r K resize-pane -D 5
bind -r J resize-pane -U 5
bind -r L resize-pane -R 5

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

set -g @plugin '2kabhishek/tmux2k'

run '~/.config/tmux/plugins/tpm/tpm'
